### ISSUE TITLE
Tests hang at coverage command

### ISSUE THREAD

**Issue by helinanever** [dart-lang/test#1423]
Steps to reproduce:
```
dart pub get
dart pub global activate coverage
dart test --file-reporter json:$HOME/test.json --coverage coverage
```

Result: the command hangs

Last message in terminal:
```
00:24 <span style="color:#859900">+140</span>: All tests passed!
```
Happens with preview release (^2.12) with latest published versions of Dart packages on Flutter channels dev, beta and master, e.g. https://github.com/dart-lang/glob/tree/1.2.0

Full command output
[log.txt](https://github.com/dart-lang/test/files/5920593/log.txt)

**Comment by mit-mit** [comment]
cc @jakemac53 @natebosch

**Comment by helinanever** [comment]
@mit-mit This is still an issue. Many pub.green builds time out due to this (e.g. around 200 builds tested with Flutter 2.0.1).

**Comment by jakemac53** [comment]
I can't repro this for vm tests but I can repro it for web tests (tried in the glob package), cc @grouma

**Comment by grouma** [comment]
I dug into this today. I found a fix but I don't know why. Basically coverage works to completion but the test process doesn't always exit. Note testing and coverage collection always works but just exiting is flaky.  This is resolved if we add a `force: true` [here](https://github.com/dart-lang/test/blob/87f31ce83a46af35914bbc2c1930c11050c676ec/pkgs/test/lib/src/runner/browser/chrome.dart#L116). We probably didn't catch this in CI because we force exit due to similar issues [here](https://github.com/dart-lang/test/blob/87f31ce83a46af35914bbc2c1930c11050c676ec/pkgs/test_core/lib/src/executable.dart#L170).

cc @natebosch for thoughts on what's going on

**Comment by yudansha** [comment]
This is still an issue. Using dart 2.12.2 and test 1.16.8
If I run `dart test --coverage="coverage"` it never ends

**Comment by grouma** [comment]
@yudansha is it flaky or does it alway fail?

**Comment by yudansha** [comment]
@grouma for me it always hangs after all tests were run and does not end.
Both on my dev machine and on the build runner (using the google dart docker image).

**Comment by grouma** [comment]
I'm not able to reproduce this with `pub run test --coverage=coverage`. I am however able to reproduce this with `dart test --coverage=coverage`. @bkonyi can you take a look?

**Comment by aaronlademann-wf** [comment]
@grouma @bkonyi @jakemac53  I can also confirm that `pub run build_runner test --file-reporter json:foo/test-results.json` passes in certain situations for us at Workiva, while the exact same test suite hangs when running `dart run build_runner test --file-reporter json:foo/test-results.json`. This is on Dart 2.13.0.

Even when it doesn't hang completely - running `dart run build_runner test` with a file-reporter takes 4-5 times longer than it does when not using a file-reporter, whereas `pub run build_runner test` with a file-reporter takes only about 2 times as long.
