### ISSUE TITLE
Tests hang on sdk versions >2.0.0-dev.28.0

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#772]
Interestingly, if you use `--pause-after-load` the tests don't hang, which indicates to me a possible race condition somewhere.

We are also using `--precompiled`, I haven't confirmed if it is related to that specifically or not. Example travis run [here](https://travis-ci.org/dart-lang/build/jobs/344839092).

You can repro this by checking out the build repo, changing to the `e2e_example` directory, and running `pub run build_runner test -- -p chrome`.

**Comment by jakemac53** [comment]
Fwiw, this also does not reproduce on windows, only on linux/mac.

**Comment by grouma** [comment]
I did a little debugging and it appears that this issue is only occurring in Chrome Headless. Normally we would forward any errors to the console but Headless gets in an odd state where it dies and restarts immediately. I was able to capture the initial error though:

[0222/133612.327435:INFO:CONSOLE(143)] "Uncaught Error: Script error for "dart_sdk", needed by: test/hello_world_custom_html_test.dart.browser_test, packages/test/src/bootstrap/browser, test/hello_world_custom_html_test, packages/test/src/runner/plugin/remote_platform_helpers, packages/test/src/util/stack_trace_mapper, packages/test/src/runner/browser/post_message_channel, packages/test/src/backend/declarer, packages/matcher/src/core_matchers, packages/test/src/runner/remote_listener, packages/stream_channel/src/close_guarantee_channel, packages/test/src/runner/suite_channel_manager, packages/source_maps/builder, packages/source_map_stack_trace/source_map_stack_trace, packages/package_resolver/src/async_package_resolver, packages/collection/src/functions, packages/collection/src/empty_unmodifiable_set, packages/collection/src/union_set, packages/async/src/future_group, packages/async/src/async_memoizer, packages/test/src/backend/state, packages/pool/pool, packages/async/src/stream_group, packages/collection/src/union_set_controller, packages/collection/src/queue_list, packages/async/src/delegate/sink, packages/test/src/util/iterable_set, packages/test/src/backend/message, packages/test/src/runner/reporter, packages/test/src/util/placeholder, packages/matcher/src/interfaces, packages/matcher/src/operator_matchers, packages/async/async, packages/matcher/src/error_matchers, packages/stack_trace/src/chain, packages/async/src/stream_sink_transformer, packages/path/path, packages/async/src/result/capture_sink, packages/test/src/runner/configuration/platform_selection, packages/boolean_selector/boolean_selector, packages/test/src/backend/platform_selector, packages/test/src/backend/test_platform, packages/source_span/src/span_exception, packages/test/src/frontend/timeout, packages/test/src/backend/operating_system, packages/test/src/runner/environment, packages/test/src/runner/plugin/environment, packages/test/src/frontend/skip, packages/test/src/backend/outstanding_callback_counter, packages/test/src/backend/closed_exception, packages/term_glyph/src/generated, packages/test/src/frontend/utils, packages/source_maps/src/source_map_span, packages/source_span/src/location, packages/source_span/src/file, packages/source_maps/src/vlq, packages/source_maps/src/utils, packages/package_resolver/src/utils, packages/package_config/packages_file, packages/http/src/base_client, packages/async/src/single_subscription_transformer, packages/async/src/delegate/stream, packages/async/src/delegate/stream_sink, packages/async/src/stream_completer, packages/async/src/stream_sink_completer, packages/async/src/null_stream_sink, packages/async/src/subscription_stream, packages/async/src/typed_stream_transformer, packages/collection/src/utils, packages/async/src/restartable_timer, packages/async/src/stream_splitter, packages/stack_trace/src/utils, packages/boolean_selector/src/parser, packages/boolean_selector/src/evaluator, packages/boolean_selector/src/ast, packages/boolean_selector/src/validator, packages/path/src/utils, packages/path/src/path_exception, packages/string_scanner/src/string_scanner, packages/source_span/src/utils, packages/source_span/src/location_mixin, packages/http/http, packages/package_config/src/util, packages/async/src/typed/stream, packages/async/src/delegate/stream_consumer, packages/http/src/exception, packages/http/src/utils, packages/http_parser/src/media_type, packages/http/src/byte_stream, packages/async/src/delegate/stream_subscription, packages/boolean_selector/src/scanner, packages/boolean_selector/src/token, packages/string_scanner/src/utils, packages/string_scanner/src/exception, packages/async/src/typed/stream_subscription, packages/async/src/delegate/event_sink, packages/http_parser/src/case_insensitive_map, packages/http_parser/src/utils, packages/http_parser/src/scan, packages/string_scanner/src/eager_span_scanner, packages/collection/src/canonicalized_map, packages/string_scanner/src/line_scanner
http://requirejs.org/docs/errors.html#scripterror", source: http://localhost:62181/hPB5Wffoky%2BxJCpSfiQErvhBEVGqltW2/test/packages/$sdk/dev_compiler/amd/require.js (143)

**Comment by grouma** [comment]
Jake and I did some further debugging. Before the above exception is thrown Chrome gives this error:

Failed to load resource: net::ERR_CACHE_WRITE_FAILURE

I've tried playing with the cache size by using the --disk-cache-size argument. Unfortunately that didn't help. It's odd that this issue is only present in Headless but it would make sense if headless has a more restrictive environment. Note that the SDK has grown a non trivial size since the last version, about 15% without accounting for the increased source map size.

We should reach out to someone on the Chrome team to figure out if the issue is coming from Headless and if there are any alternatives. We should also discuss with the DDC team to figure out if we can reduce the SDK size.

**Comment by matanlurey** [comment]
> Note that the SDK has grown a non trivial size since the last version, about 15% without accounting for the increased source map size.

That's pretty scary. Does the DDC team know why? @vsmenon

**Comment by vsmenon** [comment]
Source map fixes.  (@jmesserly)  We can play with this more, but it's a tradeoff between better stepping / hovering and source map size.

**Comment by matanlurey** [comment]
Ah that sounds reasonable. I'm guessing breaking the SDK into pieces isn't going to help much here. How is this working internally then, though, don't we also use Chrome headless? @grouma

**Comment by grouma** [comment]
Yes we default to headless inside Google3. We are still running with version: v2_0_0_dev_23_0 though. I imagine we will have difficulties rolling the next SDK because of this issue.

**Comment by grouma** [comment]
Unfortunately it is not a configurable option and you can't override it with an additional flag to the browser. I can send out a PR to temporarily disable it. Thoughts?

**Comment by matanlurey** [comment]
Yeah, I think we should disable it until the underlying issue(s) are resolved.

Should I file a separate issue to make `--no-headless` (?) an option/flag?

**Comment by grouma** [comment]
This was temporarily resolved with #773. @matanlurey feel free to open an issue to add an optional flag. There are a couple ways we can go about implementing it. Personally I think we should add a new platform called headless. This is most similar to what we have done internally. Also @nex3 has done a bunch of work to make it easy to have extensible platforms (if I recall correctly).

**Comment by jmesserly** [comment]
> > Note that the SDK has grown a non trivial size since the last version, about 15% without accounting for the increased source map size.

> Source map fixes. (@jmesserly) We can play with this more, but it's a tradeoff between better stepping / hovering and source map size.

This is a size increase to dart_sdk.js? It does include a full inline source map (https://github.com/dart-lang/sdk/issues/29830). I don't believe inline source map adds any value for the SDK (dart_sdk.js should be black boxed rather than debugged); my vote would be to remove it from dart_sdk.js

**Comment by jakemac53** [comment]
Fwiw, adding retry logic for the dart_sdk module did not seem to resolve this issue either.

**Comment by nex3** [comment]
> I don't believe inline source map adds any value for the SDK (dart_sdk.js should be black boxed rather than debugged); my vote would be to remove it from dart_sdk.js

It's very useful to be able to tell that a given line of JS came from within the SDK as opposed to user code, and it's also useful to know what the entrypoint into the SDK is. When we generate terse stack traces, we include the first SDK frame to tell users things like "this was caused within a call to `Iterable.map()`" or whatever.

Maybe it would make sense to ship the "inline" source map as a separate file? Something like `dart_sdk.js.map.js` that *just* registers the text of the source map with the library-tracking infrastructure?

**Comment by jmesserly** [comment]
> It's very useful to be able to tell that a given line of JS came from within the SDK as opposed to user code, [...]

It will step to dart_sdk.js, so that should still work.

> [...] and it's also useful to know what the entrypoint into the SDK is. When we generate terse stack traces, we include the first SDK frame to tell users things like "this was caused within a call to Iterable.map()" or whatever.

Does the SDK source map ever work? Last I checked it's emitted with dart:* URIs. Chrome seems to treat these as relative paths, but I don't think our big customer dev servers are set up to serve the SDK source files. It would be difficult, because users don't have DDC's patched SDK files available (they're an intermediate generated part of the SDK build, under `ReleaseX64/gen/utils/dartdevc/patched_sdk`), nor would much of that code make sense (many common call stack frames, like dcalls, are actually inline JS methods).

I've seen the SDK file name (e.g. operations.dart) in the stack trace in Chrome, but it doesn't seem like that would help very much by itself. If file names are important, that could be provided more cheaply without keeping the full line numbers/hover support. But there's still dart_sdk.js to know it's in the SDK, so I'm not sure the file names are necessary, given the code size cost.

> Maybe it would make sense to ship the "inline" source map as a separate file? Something like dart_sdk.js.map.js that just registers the text of the source map with the library-tracking infrastructure?

Yeah, the inline source maps are really weird, like they're working around a Chrome bug or caching issue or something. I'm not sure where the code is that uses them. It bugs me because it's a ton of extra redundant code size, and I don't know of other languages that have this problem. Inline source maps with data URIs exist, but AFAIK they work in tools and replace a separate map file, unlike ours which still require the source map. (Not to mention, any program using the magic string "SourceMap3G5a8h6JVhHfdGuDxZr1EF9GQC8y0e6u" won't work in DDC ... meaning we probably can't self host our compiler ... more of a theoretical problem, but still, the whole thing is hacky.)

**Comment by nex3** [comment]
I'm mostly concerned with generating useful stack traces for `test`'s users. We use source maps to convert from JS stack traces back to Dart-like ones that the user can understand.

> Yeah, the inline source maps are really weird, like they're working around a Chrome bug or caching issue or something. I'm not sure where the code is that uses them. It bugs me because it's a ton of extra redundant code size, and I don't know of other languages that have this problem. Inline source maps with data URIs exist, but AFAIK they work in tools and replace a separate map file, unlike ours which still require the source map. (Not to mention, any program using the magic string "SourceMap3G5a8h6JVhHfdGuDxZr1EF9GQC8y0e6u" won't work in DDC ... meaning we probably can't self host our compiler ... more of a theoretical problem, but still, the whole thing is hacky.)

Inline source maps have one extremely useful quality: they can be accessed synchronously. This is crucial for being able to generate usable stack traces from user code. With dart2js this isn't as big of a deal, since we can just eagerly download a single source map, but that's a lot less feasible for DDC where you'd have to track down and eagerly download all the source maps for all the modules that are transitively loaded by the entrypoint. Just being able to look up source map strings from module names as-needed is much easier.

**Comment by jakemac53** [comment]
@grouma is this issue resolved now?

**Comment by grouma** [comment]
This is no longer an issue as of Dart VM version: 2.0.0-dev.49.0.
